# huginn

name: "dark overlord of data"
description: "if it's not dark, it's not data"

disqus: darkoverlordofdata
source: ./template
destination: ../master
port: 53610
url: http://darkoverlordofdata.com

marked:
  gfm: true
  tables: true
  breaks: false
  pedantic: false
  sanitize: true
  smartLists: true
  smartypants: false

plugins:
  - huginn-asset-bundler
  - huginn-tag-cloud

tag_page_layout: tag_page
tag_page_dir: tag

asset_bundler:
  compress:
    js: true
    css: true
  base_path: /assets/
  shim: ''
  server_url: //cdn.darkoverlordofdata.com/
  remove_bundled: false
  dev: true
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"