# huginn

name: "dark overlord of data"
description: "if it's not dark, it's not data"

disqus: d16a
source: ./template
destination: ./gh-pages
port: 53610
url: http://darkoverlordofdata.com

serve:
  - ./gh-pages


plugins:
  - huginn-asset-bundler
  - huginn-tag-cloud

tag_page_layout: tag_page
tag_page_dir: tag

asset_bundler:
  compress:
    js: true
    css: true
  base_path: /assets/
  shim: ''
  server_url: //cdn.darkoverlordofdata.com/
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"